development:
  adapter: mysql
  database: cezobal_development
  username: root
  password:
  host: localhost
  encoding: utf8

test:
  adapter: mysql
  database: cezobal_test
  username: root
  password:
  host: localhost
  encoding: utf8

production:
  adapter: mysql
  database: cezobal_production
  username: root
  password: 
  host: localhost
  encoding: utf8

